# -*- coding: utf-8 -*-
"""list,tuple,dictionary,sets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Po_KQ3QonRHnJBQ1UPhXxjGaeLrQCv4D
"""

# 🔹 1. LISTS
fruits = ['apple', 'banana', 'cherry', 'apple']
print("Original list:", fruits)
print("First fruit:", fruits[0])

fruits.append('kiwi')
print("after appending:",fruits)

fruits.remove('apple')
print("after removing:",fruits)

print("number of fruits:",len(fruits))

# 2.TUPLES
dem=(10,20,39)
print("tuple:",dem)

print("second ele:",dem[1])

# 3.SETS
unique_numbers={1,2,3,2,1}
print("sets:",unique_numbers)

unique_numbers.add(7)
print("after adding:",unique_numbers)

unique_numbers.remove(7)
print("after removing:",unique_numbers)

set_a={1,2,3}
set_b={3,6,7}
print("Union:",set_a | set_b)
print("Intersection:",set_a & set_b)
print("Difference:",set_a - set_b)

student = {
    'name': 'Alice',
    'age': 21,
    'course': 'Python'
}
print("Dictionary:", student)

print("student name:",student['name'])

# Add or update value
student['grade'] = 'A'
print("After adding grade:", student)

# Remove a key
del student['age']
print("After deleting age:", student)

# Loop through dictionary
for key, value in student.items():
    print(f"{key}: {value}")

keys = ['id', 'name', 'marks']
values = [5, 'navya', 95]
student_info = dict(zip(keys, values))
print("Student Info from zip:", student_info)