# -*- coding: utf-8 -*-
"""NumPy_Exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C-QRFWY5RnEGIAtGEt_5WlIHoScMWBbh
"""

import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")
# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).

# Your code for Task 1 here:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
arr1_1 = np.arange(100)

# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).
arr1_4 = np.random.randint(10, 51, size=(5, 5))

# Display the arrays
print("\narr1_1:")
print(arr1_1)

print("\narr1_2:")
print(arr1_2)

print("\narr1_3:")
print(arr1_3)

print("\narr1_4:")
print(arr1_4)

print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1 Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.
val2_1 = data[2, 3]

# 2.2 Extract the first row. Store it in 'row2_2'.
row2_2 = data[0]

# 2.3 Extract the last column. Store it in 'col2_3'.
col2_3 = data[:, -1]

# 2.4 Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1.
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Using boolean indexing, select all elements in 'data' that are greater than 100.
filtered_elements2_5 = data[data > 100]

# Display the results
print("2.1:", val2_1)
print("\n2.2:")
print(row2_2)

print("\n2.3:")
print(col2_3)

print("\n2.4:")
print(sub_arr2_4)

print("\n2.5:")
print(filtered_elements2_5)

print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))  # Random 4x5 array with values 1 to 20

# 3.1 Replace elements less than 10 with 0, keep others unchanged
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count the number of even elements
even_count3_3 = np.count_nonzero(arr3_1 % 2 == 0)

# Display the results
print("Original Array (arr3_1):")
print(arr3_1)

print("\nModified Array (arr3_2):")
print(arr3_2)

print("\nNumber of even elements:")
print(even_count3_3)

print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

# 4.1 Calculate the sum of all elements
sum4_1 = np.sum(arr4_1)

# 4.2 Calculate the mean of each column
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3 Find the maximum value in each row
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4 Calculate the standard deviation of the entire array
std4_4 = np.std(arr4_1)

# Display the results
print("Sum of all elements:", sum4_1)

print("\nMean of each column:")
print(mean_cols4_2)

print("\nMaximum value in each row:")
print(max_rows4_3)

print("\nStandard deviation of the array:")
print(std4_4)

import numpy as np
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])
sum4_1 = np.sum(arr4_1)
mean_cols4_2 = np.mean(arr4_1, axis=0)
max_rows4_3 = np.max(arr4_1, axis=1)
std4_4 = np.std(arr4_1)
print("Sum of all elements:", sum4_1)
print("Mean of each column:", mean_cols4_2)
print("Maximum value in each row:", max_rows4_3)
print("Standard deviation of the entire array:", std4_4)

print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)  # 1D array from 0 to 23
reshaped_arr5_2 = arr5_1.reshape(4, 6)
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
flattened_arr5_4_ravel = reshaped_arr5_2.ravel()
flattened_arr5_4_flatten = reshaped_arr5_2.flatten()
print("Original Array:")
print(arr5_1)

print("\nReshaped to 4x6:")
print(reshaped_arr5_2)

print("\nReshaped to 2x3x4:")
print(reshaped_arr5_3)

print("\nFlattened using ravel():")
print(flattened_arr5_4_ravel)

print("\nFlattened using flatten():")
print(flattened_arr5_4_flatten)

print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])
result6_1 = arr6_1 + scalar
result6_2 = arr6_1 + vector
print("Original Array:")
print(arr6_1)

print("\nResult after adding scalar (10):")
print(result6_1)

print("\nResult after adding vector [100, 200, 300]:")
print(result6_2)

# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])


view_arr7 = original_arr7[:]
view_arr7[0] = 99
print("Original array after modifying view:")
print(original_arr7)
print("View array:")
print(view_arr7)
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0
print("\nOriginal array after modifying copy:")
print(original_arr7)
print("Copy array:")
print(copy_arr7)

# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# 9.1 Sort 'arr9_1' in ascending order.
sorted_arr9_1 = np.sort(arr9_1)

# 9.2 Sort 'arr9_2d' along columns (each column sorted independently).
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3 Find the indices where the value 9 is present in 'arr9_1'.
idx9_3 = np.where(arr9_1 == 9)

# 9.4 Find the index of the maximum value in 'arr9_1'.
max_idx9_4 = np.argmax(arr9_1)

# Print the results
print("Original 1D Array:")
print(arr9_1)

print("\nSorted 1D Array:")
print(sorted_arr9_1)

print("\nOriginal 2D Array:")
print(arr9_2d)

print("\nColumns Sorted:")
print(sorted_cols9_2)

print("\nIndex of value 9:")
print(idx9_3)

print("\nIndex of maximum value:")
print(max_idx9_4)