# -*- coding: utf-8 -*-
"""U7 — DS Lifecycle & Data Sources: Lab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fav2X030SG9_CsGVq66Wg9TbsupG50x2
"""

# Core imports for the whole lab
import pandas as pd
import json

print('Setup complete. pandas', pd.__version__)

lifecycle = [
    'Define',
    'Collect',
    'Prepare',
    'Explore',
    'Model',
    'Evaluate',
    'Deploy',
    'Monitor',
]
for i, stage in enumerate(lifecycle, start=1):
    print(f'{i}. {stage}')

what_happens = {
    'Define':   'turn a business question into an ML problem',
    'Collect':  'pull data from files, databases, APIs',
    'Prepare':  'clean missing values, fix types, engineer features',
    'Explore':  'summarise & visualise to find patterns',
    'Model':    'train and tune algorithms',
    'Evaluate': 'measure performance on unseen data',
    'Deploy':   'put the model into production',
    'Monitor':  'track performance and retrain as needed',
}
for stage, desc in what_happens.items():
    print(f'{stage:9s} -> {desc}')

crisp_dm = [
    'Business Understanding',
    'Data Understanding',
    'Data Preparation',
    'Modeling',
    'Evaluation',
    'Deployment',
]
for i, phase in enumerate(crisp_dm, start=1):
    print(f'{i}. {phase}')

mapping = {
    'Define':   'Business Understanding',
    'Collect':  'Data Understanding',
    'Explore':  'Data Understanding',
    'Prepare':  'Data Preparation',
    'Model':    'Modeling',
    'Evaluate': 'Evaluation',
    'Deploy':   'Deployment',
    'Monitor':  'Deployment',
}
for stage, phase in mapping.items():
    print(f'{stage:9s} -> {phase}')

examples = {
    'a SQL users table':        'structured',
    'a CSV of sales':           'structured',
    'a JSON API response':      'semi-structured',
    'an XML config file':       'semi-structured',
    'a folder of photos':       'unstructured',
    'customer review text':     'unstructured',
}
for item, kind in examples.items():
    print(f'{kind:16s} <- {item}')

def classify(fmt):
    fmt = fmt.lower()
    if fmt in ('csv', 'sql', 'parquet', 'excel', 'xlsx'):
        return 'structured'
    if fmt in ('json', 'xml', 'yaml', 'log'):
        return 'semi-structured'
    return 'unstructured'   # text, image, audio, video, ...

for fmt in ['csv', 'json', 'jpg', 'sql', 'xml', 'mp3']:
    print(f'{fmt:6s} -> {classify(fmt)}')

sample = pd.DataFrame({
    'name':   ['Ana', 'Bo', 'Cy', 'Di'],
    'age':    [30, 25, 41, 38],
    'city':   ['Pune', 'Delhi', 'Pune', 'Hyderabad'],
    'spend':  [120.5, 80.0, 200.2, 150.0],
})
sample.to_csv('people.csv', index=False)

df = pd.read_csv('people.csv')
df.head()

print('shape :', df.shape)
print()
print('dtypes:')
print(df.dtypes)
print()
df.describe(include='all')

records = [
    {'id': 1, 'user': {'name': 'Ana', 'city': 'Pune'}, 'spend': 120.5},
    {'id': 2, 'user': {'name': 'Bo',  'city': 'Delhi'}, 'spend': 80.0},
]
json_df = pd.json_normalize(records)
json_df

import requests

API_URL = 'https://jsonplaceholder.typicode.com/users'   # a free demo API

# Pattern: GET the URL -> parse JSON -> build a DataFrame.
# We wrap it in try/except so the lab still runs if you're offline;
# in that case we fall back to a small inline sample.
try:
    resp = requests.get(API_URL, timeout=10)
    resp.raise_for_status()
    data = resp.json()
    print('Fetched', len(data), 'records from the live API.')
except Exception as e:
    print('Network unavailable (', type(e).__name__, ') - using inline sample.')
    data = [
        {'id': 1, 'name': 'Leanne Graham',  'username': 'Bret',     'email': 'sincere@april.biz'},
        {'id': 2, 'name': 'Ervin Howell',   'username': 'Antonette','email': 'shanna@melissa.tv'},
        {'id': 3, 'name': 'Clementine Bauch','username': 'Samantha','email': 'nathan@yesenia.net'},
    ]

api_df = pd.json_normalize(data)
api_df.head()

print('shape:', api_df.shape)
# keep just a few useful columns (these exist in both live & sample data)
cols = [c for c in ['id', 'name', 'username', 'email'] if c in api_df.columns]
api_df[cols].head()